# Generated by Django 4.1.4 on 2023-02-03 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dashboards',
            new_name='Package',
        ),
    ]
