# Generated by Django 4.1.6 on 2023-10-02 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_is_manager_staff_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_manager',
        ),
    ]
