# Generated by Django 4.1.6 on 2023-10-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userprofile_is_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
