# Generated by Django 4.1.6 on 2023-10-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_manager_status_staff_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
