# Generated by Django 4.1.6 on 2023-10-03 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_staff_is_manager_staff_is_staff_delete_manager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
