# Generated by Django 4.1.6 on 2023-03-12 18:00

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dportal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dportal',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='dportal',
            name='document',
        ),
        migrations.AddField(
            model_name='dportal',
            name='file',
            field=models.FileField(blank=True, upload_to='dportal'),
        ),
        migrations.AddField(
            model_name='dportal',
            name='thematic_area',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dportal',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
