# Generated by Django 4.1.6 on 2023-03-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dportal', '0002_remove_dportal_banner_remove_dportal_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dportal',
            name='publish',
            field=models.IntegerField(default=0),
        ),
    ]
