# Generated by Django 4.1.6 on 2023-05-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dportal', '0003_dportal_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dportal',
            name='file',
            field=models.FileField(blank=True, max_length=500, upload_to='dportal'),
        ),
        migrations.AlterField(
            model_name='dportal',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
