# Generated by Django 4.1.6 on 2023-05-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dportal', '0004_alter_dportal_file_alter_dportal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dportal',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
