# Generated by Django 4.1.6 on 2023-09-14 12:20

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dportal', '0005_alter_dportal_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=500)),
                ('age', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=500)),
                ('district', models.CharField(max_length=500)),
                ('region', models.CharField(max_length=500)),
                ('main_complaint', ckeditor_uploader.fields.RichTextUploadingField()),
                ('history_of_present_illness', ckeditor_uploader.fields.RichTextUploadingField()),
                ('review_of_other_systems', ckeditor_uploader.fields.RichTextUploadingField()),
                ('past_medical_history', ckeditor_uploader.fields.RichTextUploadingField()),
                ('gynaecological_history', ckeditor_uploader.fields.RichTextUploadingField()),
                ('family_social_history', ckeditor_uploader.fields.RichTextUploadingField()),
                ('dietary_history', ckeditor_uploader.fields.RichTextUploadingField()),
                ('general_examination', ckeditor_uploader.fields.RichTextUploadingField()),
                ('local_examination', ckeditor_uploader.fields.RichTextUploadingField()),
                ('systemic_examination', ckeditor_uploader.fields.RichTextUploadingField()),
                ('provisional_diagnosis', ckeditor_uploader.fields.RichTextUploadingField()),
                ('differential_diagnosis', ckeditor_uploader.fields.RichTextUploadingField()),
                ('final_diagnosis', ckeditor_uploader.fields.RichTextUploadingField()),
                ('radiological', ckeditor_uploader.fields.RichTextUploadingField()),
                ('laboratory', ckeditor_uploader.fields.RichTextUploadingField()),
                ('doctors_remarks', ckeditor_uploader.fields.RichTextUploadingField()),
                ('medicines', ckeditor_uploader.fields.RichTextUploadingField()),
                ('treatment_regime', ckeditor_uploader.fields.RichTextUploadingField()),
                ('recommendation', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
