# Generated by Django 4.1.6 on 2023-10-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dportal', '0006_patientdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='facility',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
