# Generated by Django 4.1.6 on 2023-11-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dportal', '0007_patientdata_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
