# Generated by Django 4.1.6 on 2023-02-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='description',
        ),
        migrations.AddField(
            model_name='news',
            name='content_photo_three',
            field=models.ImageField(blank=True, null=True, upload_to='news'),
        ),
        migrations.AddField(
            model_name='news',
            name='publish',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='news',
            name='banner',
            field=models.ImageField(blank=True, upload_to='news'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_photo_one',
            field=models.ImageField(blank=True, null=True, upload_to='news'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content_photo_two',
            field=models.ImageField(blank=True, null=True, upload_to='news'),
        ),
        migrations.AlterField(
            model_name='news',
            name='publisher',
            field=models.CharField(max_length=100),
        ),
    ]
