# Generated by Django 4.1.6 on 2023-02-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_news_description_news_content_photo_three_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='reject',
            field=models.IntegerField(default=0),
        ),
    ]
