# Generated by Django 4.1.6 on 2023-03-11 08:04

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_news_content_photo_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
