# Generated by Django 4.1.6 on 2023-03-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_remove_news_content_photo_one_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='thematic_area',
            field=models.IntegerField(default=0),
        ),
    ]
