# Generated by Django 4.1.6 on 2023-03-16 13:53

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_news_thematic_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='banner',
        ),
        migrations.AddField(
            model_name='news',
            name='header_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='PNG', keep_meta=True, quality=100, scale=0.5, size=[1400, 600], upload_to='news'),
        ),
        migrations.AddField(
            model_name='news',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='PNG', keep_meta=True, quality=100, scale=0.5, size=[600, 400], upload_to='news'),
        ),
    ]
