# Generated by Django 4.1.6 on 2023-05-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_alter_news_slug_alter_news_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='file',
            field=models.FileField(blank=True, max_length=500, upload_to='news'),
        ),
    ]
