# Generated by Django 4.1.6 on 2023-02-13 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(blank=True, upload_to='colab'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='sponsor_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsor',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='website_url',
            field=models.CharField(default='url', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
