# Generated by Django 4.1.6 on 2023-02-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0002_sponsor_created_at_sponsor_logo_sponsor_sponsor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(blank=True, upload_to='sponsor'),
        ),
    ]
