# Generated by Django 4.1.6 on 2023-03-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0003_alter_sponsor_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='website_url',
            field=models.URLField(max_length=100),
        ),
    ]
