# Generated by Django 4.1.4 on 2023-01-21 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('title', models.CharField(default=None, max_length=100)),
                ('bio', models.TextField()),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(max_length=100)),
                ('affiliate', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, default=None, max_length=255, upload_to='media/team')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
