# Generated by Django 4.1.6 on 2023-02-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_rename_firstname_team_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='bio',
            field=models.TextField(max_length=2000),
        ),
    ]
