# Generated by Django 4.1.6 on 2023-02-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_team_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='bio',
            field=models.TextField(max_length=5000),
        ),
    ]
