# Generated by Django 4.1.6 on 2023-02-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_team_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(blank=True, default=None, max_length=255, upload_to='team'),
        ),
    ]
