# Generated by Django 4.1.6 on 2023-05-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_alter_team_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='affiliation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='email',
            field=models.EmailField(max_length=500),
        ),
        migrations.AlterField(
            model_name='team',
            name='first_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='team',
            name='last_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='team',
            name='phone',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='photo',
            field=models.ImageField(blank=True, default=None, max_length=500, upload_to='team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='title',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
