# Generated by Django 4.1.6 on 2023-03-16 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_udomai_delete_community'),
    ]

    operations = [
        migrations.RenameField(
            model_name='udomai',
            old_name='yof',
            new_name='yos',
        ),
    ]
