# Generated by Django 4.1.6 on 2023-03-17 13:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_rename_yof_udomai_yos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AI4D',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('college', models.IntegerField(default=0)),
                ('programme', models.CharField(max_length=200)),
                ('yos', models.IntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
