# Generated by Django 4.1.6 on 2023-03-17 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_ai4d'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ai4d',
            old_name='programme',
            new_name='affiliation',
        ),
        migrations.RenameField(
            model_name='ai4d',
            old_name='college',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='ai4d',
            old_name='yos',
            new_name='field',
        ),
    ]
