# Generated by Django 4.1.6 on 2023-02-20 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='body',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='description',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='document',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='status',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='title',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='conference',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
