# Generated by Django 4.1.6 on 2023-05-06 05:29

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0002_remove_conference_banner_remove_conference_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallPaperAAIAC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('title', models.CharField(default=None, max_length=500)),
                ('bio', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=500, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(max_length=500)),
                ('status', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, default=None, max_length=500, upload_to='team')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationAAIAC',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('title', models.CharField(default=None, max_length=500)),
                ('bio', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=500, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(max_length=500)),
                ('status', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, default=None, max_length=500, upload_to='team')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
