# Generated by Django 4.1.6 on 2023-03-12 14:27

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('thumbnail', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='PNG', keep_meta=True, quality=100, scale=0.5, size=[600, 400], upload_to='blog')),
                ('header_image', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='PNG', keep_meta=True, quality=100, scale=0.5, size=[600, 400], upload_to='blog')),
                ('description', models.TextField()),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('thematic_area', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('publish', models.IntegerField(default=0)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
