# Generated by Django 4.1.6 on 2023-02-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content_photo_one',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content_photo_two',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='publisher',
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='header_image',
            field=models.ImageField(blank=True, upload_to='blog'),
        ),
        migrations.AddField(
            model_name='blog',
            name='publish',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
