# Generated by Django 4.1.6 on 2023-03-16 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0003_call_file_alter_call_header_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='author',
            new_name='publisher',
        ),
    ]
