# Generated by Django 4.1.6 on 2023-05-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0004_rename_author_call_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='file',
            field=models.FileField(blank=True, max_length=500, upload_to='call'),
        ),
        migrations.AlterField(
            model_name='call',
            name='slug',
            field=models.SlugField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
