# Generated by Django 4.1.6 on 2023-02-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='colab',
            old_name='name',
            new_name='partner_name',
        ),
        migrations.RemoveField(
            model_name='colab',
            name='about',
        ),
        migrations.AddField(
            model_name='colab',
            name='website_url',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colab',
            name='logo',
            field=models.ImageField(blank=True, upload_to='colab'),
        ),
    ]
