# Generated by Django 4.1.6 on 2023-03-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0003_rename_partner_name_colab_colab_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colab',
            name='website_url',
            field=models.URLField(max_length=100),
        ),
    ]
