# Generated by Django 4.1.6 on 2023-05-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colab', '0005_colab_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colab',
            name='colab_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='colab',
            name='logo',
            field=models.ImageField(blank=True, max_length=500, upload_to='colab'),
        ),
        migrations.AlterField(
            model_name='colab',
            name='website_url',
            field=models.URLField(max_length=500),
        ),
    ]
