# Generated by Django 4.1.6 on 2023-03-17 16:33

import ckeditor_uploader.fields
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='project',
            name='document',
        ),
        migrations.AddField(
            model_name='project',
            name='header_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='PNG', keep_meta=True, quality=100, scale=0.5, size=[1400, 600], upload_to='news'),
        ),
        migrations.AddField(
            model_name='project',
            name='publish',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='reject',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='thematic_area',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='PNG', keep_meta=True, quality=100, scale=0.5, size=[650, 600], upload_to='news'),
        ),
        migrations.AlterField(
            model_name='project',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
