# Generated by Django 4.1.6 on 2023-03-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_workshop_created_at_workshop_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='workshop_url',
            field=models.CharField(max_length=200),
        ),
    ]
