# Generated by Django 4.1.6 on 2023-03-18 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_alter_workshop_workshop_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='published',
            new_name='publish',
        ),
    ]
