# Generated by Django 4.1.6 on 2023-05-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_rename_published_workshop_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='workshop_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='workshop_url',
            field=models.CharField(max_length=500),
        ),
    ]
