# Generated by Django 4.1.4 on 2023-01-21 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jupyinter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.IntegerField(default=0)),
                ('uploads', models.ImageField(blank=True, max_length=200, upload_to='media/jupyinter')),
                ('slug', models.SlugField(unique=True)),
                ('status', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
