# Generated by Django 4.1.6 on 2023-03-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_rename_name_partner_partner_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='website_url',
            field=models.URLField(max_length=100),
        ),
    ]
