# Generated by Django 4.1.6 on 2023-03-25 14:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0003_alter_partner_website_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
