# Generated by Django 4.1.6 on 2023-05-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_partner_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, max_length=500, upload_to='partner'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='partner_name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='partner',
            name='website_url',
            field=models.URLField(max_length=500),
        ),
    ]
